# Generated by Django 5.2.14 on 2026-05-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='name',
            field=models.CharField(choices=[('BASIC', 'Basic'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium'), ('ELITE', 'Elite'), ('CUSTOM', 'Custom')], default='BASIC', max_length=20),
        ),
        migrations.AlterModelTable(
            name='subscription',
            table='subscription',
        ),
    ]
