# Generated by Django 5.2.14 on 2026-05-29 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_remove_member_notes_alter_member_is_active'),
        ('subscription', '0002_alter_subscription_name_alter_subscription_table'),
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='name',
            field=models.CharField(default='BASIC', max_length=20),
        ),
        migrations.CreateModel(
            name='GymMemberShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
                ('subsrciption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.subscription')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trainer.trainer')),
            ],
            options={
                'db_table': 'gymmembership',
            },
        ),
    ]
