# Generated by Django 5.2.14 on 2026-05-31 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_alter_subscription_name_gymmembership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gymmembership',
            old_name='subsrciption',
            new_name='subscription',
        ),
    ]
