# Generated by Django 5.2.14 on 2026-05-31 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_rename_subsrciption_gymmembership_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymmembership',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
