# Generated by Django 5.2.14 on 2026-06-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_alter_gymmembership_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymmembership',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=20),
        ),
    ]
