# Generated by Django 5.2.14 on 2026-06-07 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0002_remove_member_notes_alter_member_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='TXN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Initial', 'Initial'), ('Completed', 'Completed'), ('Pending', 'Pending'), ('User Cancelled', 'User Cancelled')], default='Initial', max_length=20)),
                ('txn_id', models.CharField(blank=True, max_length=50, null=True)),
                ('pidx', models.CharField(blank=True, max_length=30, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='member.member')),
            ],
        ),
    ]
