# Generated by Django 5.2.14 on 2026-06-02 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('member', '0002_remove_member_notes_alter_member_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('member', 'attendance_date')},
        ),
    ]
